blockExoticSubdeps: true
catalog:
  '@nestjs/common': ^11.1.28
  '@nestjs/core': ^11.1.28
  '@types/node': ^24.13.3
  jest: ^30.4.2
  rabbitmq-client: ^5.0.8
  ts-jest: ^29.4.11
  tsdown: ^0.22.9
  typescript: ^5.9.3
  zod: ^4.4.3
catalogMode: strict
ignoreDepScripts: true
minimumReleaseAge: 1080 # 15 days
minimumReleaseAgeExclude:
  - '@jsnw/*'
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20160 # 30 days
