export const RABBITMQ_INSTANCE_DEFAULT_NAME = 'default';
export const RABBITMQ_INSTANCE_TOKEN_PREFIX = 'RABBITMQ_INSTANCE_' as const;
export const RABBITMQ_SUBSCRIBE_METADATA_KEY = Symbol('RABBITMQ_SUBSCRIBE_METADATA');
